services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-export-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true